project:
  type: website

  preview:
    port: 1234
    browser: false

  output-dir: docs
  execute-dir: project

  post-render:
    - helpers/generate_redirects.R
    - helpers/copy_qmd_files.R

  render:
    - "./*.qmd"
    - "tutorials/"

website:
  title: "Language Technology and Data Analysis Laboratory (LADAL)"
  search: false
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT
      - href: events.qmd
        text: EVENTS
      - href: tutorials.qmd
        text: TUTORIALS
      - href: tools.qmd
        text: TOOLS
      - href: resources.qmd
        text: RESOURCES
      - href: contact.qmd
        text: CONTACT
  google-analytics: "G-VSGK4KYDQZ"

format:
  html:
    toc: true            
    toc-depth: 2         
    toc-location: left
    toc-scroll: true
    smooth-scroll: true
    theme: minima
    css: css/styles.css
    include-in-header: "assets/custom_header.html"
resources:
  images

execute:
  cache: true

bibliography: assets/bibliography.bib

params:
  base_url: "https://binderhub.atap-binder.cloud.edu.au/v2/gh/SLCLADAL/interactive-notebooks-environment/main"
  repo_url: "https://github.com/SLCLADAL/interactive-notebooks"
  notebook_path: "notebooks/regex_cb.ipynb"

directories:
  - tutorials:
      format: html