project:
  type: website
  preview:
    port: 1234
    browser: false
  output-dir: docs
  execute-dir: project
  post-render:
    - helpers/generate_redirects.R
  render:
    - "./*.qmd"
    - "tutorials/"
  resources:
    - images
    - CNAME
    - ".nojekyll"
    - robots.txt

website:
  title: "LADAL"
  site-url: "https://ladal.edu.au"
  search: false
  navbar:
    pinned: true
    background: "#51247A"
    foreground: white
    left:
      - href: index.qmd
        text: HOME
      - text: ABOUT
        menu:
          - href: about.qmd
            text: About LADAL
          - href: about.qmd#directors
            text: People & Collaborators
          - href: about.qmd#citing
            text: Citing & Licensing
          - href: about.qmd#faq
            text: FAQs
      - text: TUTORIALS
        menu:
          - href: tutorials.qmd
            text: About Tutorials
          - href: tutorials.qmd#data-science-basics
            text: Data Science Basics
          - href: tutorials.qmd#r-basics
            text: R Basics
          - href: tutorials.qmd#data-visualisation
            text: Data Collection and Acquisition
          - href: tutorials.qmd#data-collection
            text: Data Visualisation
          - href: tutorials.qmd#statistics
            text: Statistics
          - href: tutorials.qmd#text-analytics
            text: Text Analytics
      - text: COURSES
        menu:
          - href: courses.qmd
            text: About Courses
          - href: courses.qmd#short-courses
            text: Short Courses
          - href: courses.qmd#long-courses
            text: Long Courses
      - text: TOOLS
        menu:
          - href: tools.qmd
            text: About Tools
          - href: tools.qmd#shiny-tools
            text: Shiny Tools
          - href: tools.qmd#jupyter-tools
            text: Juypter Notebooks Tools
      - href: events.qmd
        text: EVENTS
      - text: RESOURCES
        menu:
          - href: resources.qmd
            text: Guides & Resources
          - href: contact.qmd
            text: Contribute to LADAL
      - href: contact.qmd
        text: CONTACT
  google-analytics: "G-RM0VHZB3CG"
  repo-url: "https://github.com/SLCLADAL/ladal"

format:
  html:
    date-format: "YYYY"
    canonical-url: true
    toc: true
    toc-depth: 2
    toc-location: left
    toc-scroll: true
    smooth-scroll: true
    theme: minima
    css: css/styles.css
    include-in-header: "assets/custom_header.html"
    include-after-body: "assets/custom_footer.html"
    anchor-sections: true

execute:
  cache: true

bibliography: assets/bibliography.bib

params:
  base_url: "https://binderhub.atap-binder.cloud.edu.au/v2/gh/SLCLADAL/interactive-notebooks-environment/main"
  repo_url: "https://github.com/SLCLADAL/interactive-notebooks"
  notebook_path: "notebooks/regex_cb.ipynb"

directories:
  - tutorials:
      format: html